//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmamusumeResponseAnalyzer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmamusumeResponseAnalyzer.Localization.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]Error reading the configuration file, regenerated, please change the settings again[/].
        /// </summary>
        internal static string I18N_ConfigLoadError {
            get {
                return ResourceManager.GetString("I18N_ConfigLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]Type error reading configuration &lt;{0}&gt;: Requested type was {1}, but actual type was {2}[/].
        /// </summary>
        internal static string I18N_ConfigTypeCastError {
            get {
                return ResourceManager.GetString("I18N_ConfigTypeCastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string I18N_Debug {
            get {
                return ResourceManager.GetString("I18N_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide SelectIndex.
        /// </summary>
        internal static string I18N_DisableSelectIndex {
            get {
                return ResourceManager.GetString("I18N_DisableSelectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip DMM to start the game.
        /// </summary>
        internal static string I18N_DMMLaunch {
            get {
                return ResourceManager.GetString("I18N_DMMLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable game acceleration feature.
        /// </summary>
        internal static string I18N_EnableNetFilter {
            get {
                return ResourceManager.GetString("I18N_EnableNetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string I18N_Events {
            get {
                return ResourceManager.GetString("I18N_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force update using GitHub.
        /// </summary>
        internal static string I18N_ForceUseGithubToUpdate {
            get {
                return ResourceManager.GetString("I18N_ForceUseGithubToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string I18N_Language {
            get {
                return ResourceManager.GetString("I18N_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detect.
        /// </summary>
        internal static string I18N_Language_AutoDetect {
            get {
                return ResourceManager.GetString("I18N_Language_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string I18N_Language_English {
            get {
                return ResourceManager.GetString("I18N_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string I18N_Language_Japanese {
            get {
                return ResourceManager.GetString("I18N_Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        internal static string I18N_Language_SimplifiedChinese {
            get {
                return ResourceManager.GetString("I18N_Language_SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data from localization plugin.
        /// </summary>
        internal static string I18N_LoadLocalizedData {
            get {
                return ResourceManager.GetString("I18N_LoadLocalizedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string I18N_Localization {
            get {
                return ResourceManager.GetString("I18N_Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization file path.
        /// </summary>
        internal static string I18N_LocalizedDataPath {
            get {
                return ResourceManager.GetString("I18N_LocalizedDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide skill learning recommendations for maximizing evaluation points.
        /// </summary>
        internal static string I18N_MaximiumGradeSkillRecommendation {
            get {
                return ResourceManager.GetString("I18N_MaximiumGradeSkillRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        internal static string I18N_NetworkProxy {
            get {
                return ResourceManager.GetString("I18N_NetworkProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string I18N_Other {
            get {
                return ResourceManager.GetString("I18N_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze monthly race competitions.
        /// </summary>
        internal static string I18N_ParseChampionsRaceStartResponse {
            get {
                return ResourceManager.GetString("I18N_ParseChampionsRaceStartResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze circle members.
        /// </summary>
        internal static string I18N_ParseCircleResponse {
            get {
                return ResourceManager.GetString("I18N_ParseCircleResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze friend&apos;s horse victories.
        /// </summary>
        internal static string I18N_ParseFriendSearchResponse {
            get {
                return ResourceManager.GetString("I18N_ParseFriendSearchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze practice races.
        /// </summary>
        internal static string I18N_ParsePracticeRaceRaceStartResponse {
            get {
                return ResourceManager.GetString("I18N_ParsePracticeRaceRaceStartResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze room matches.
        /// </summary>
        internal static string I18N_ParseRoomMatchRaceStartResponse {
            get {
                return ResourceManager.GetString("I18N_ParseRoomMatchRaceStartResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze upbringing events.
        /// </summary>
        internal static string I18N_ParseSingleModeCheckEventResponse {
            get {
                return ResourceManager.GetString("I18N_ParseSingleModeCheckEventResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze arena opponent attributes.
        /// </summary>
        internal static string I18N_ParseTeamStadiumOpponentListResponse {
            get {
                return ResourceManager.GetString("I18N_ParseTeamStadiumOpponentListResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze turnip horse victories.
        /// </summary>
        internal static string I18N_ParseTrainedCharaLoadResponse {
            get {
                return ResourceManager.GetString("I18N_ParseTrainedCharaLoadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration server address.
        /// </summary>
        internal static string I18N_ProxyHost {
            get {
                return ResourceManager.GetString("I18N_ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration server password.
        /// </summary>
        internal static string I18N_ProxyPassword {
            get {
                return ResourceManager.GetString("I18N_ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration server port.
        /// </summary>
        internal static string I18N_ProxyPort {
            get {
                return ResourceManager.GetString("I18N_ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration server type.
        /// </summary>
        internal static string I18N_ProxyServerType {
            get {
                return ResourceManager.GetString("I18N_ProxyServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration server username.
        /// </summary>
        internal static string I18N_ProxyUsername {
            get {
                return ResourceManager.GetString("I18N_ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save communication packets for debugging.
        /// </summary>
        internal static string I18N_SaveResponseForDebug {
            get {
                return ResourceManager.GetString("I18N_SaveResponseForDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show trainer head information.
        /// </summary>
        internal static string I18N_ShowCommandInfo {
            get {
                return ResourceManager.GetString("I18N_ShowCommandInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string I18N_Update {
            get {
                return ResourceManager.GetString("I18N_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write round information to file for AI reading.
        /// </summary>
        internal static string I18N_WriteAIInfo {
            get {
                return ResourceManager.GetString("I18N_WriteAIInfo", resourceCulture);
            }
        }
    }
}
