//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmamusumeResponseAnalyzer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmamusumeResponseAnalyzer.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳过DMM启动游戏.
        /// </summary>
        public static string ConfigSet_DMMLaunch {
            get {
                return ResourceManager.GetString("ConfigSet_DMMLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用游戏加速功能.
        /// </summary>
        public static string ConfigSet_EnableNetFilter {
            get {
                return ResourceManager.GetString("ConfigSet_EnableNetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件.
        /// </summary>
        public static string ConfigSet_Events {
            get {
                return ResourceManager.GetString("ConfigSet_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强制使用GitHub更新.
        /// </summary>
        public static string ConfigSet_ForceUseGithubToUpdate {
            get {
                return ResourceManager.GetString("ConfigSet_ForceUseGithubToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载本地化插件的数据.
        /// </summary>
        public static string ConfigSet_LoadLocalizedData {
            get {
                return ResourceManager.GetString("ConfigSet_LoadLocalizedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 给出评价点最大化的技能学习建议.
        /// </summary>
        public static string ConfigSet_MaximiumGradeSkillRecommendation {
            get {
                return ResourceManager.GetString("ConfigSet_MaximiumGradeSkillRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析每月大赛比赛.
        /// </summary>
        public static string ConfigSet_ParseChampionsRaceStartResponse {
            get {
                return ResourceManager.GetString("ConfigSet_ParseChampionsRaceStartResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析好友种马胜鞍.
        /// </summary>
        public static string ConfigSet_ParseFriendSearchResponse {
            get {
                return ResourceManager.GetString("ConfigSet_ParseFriendSearchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析练习赛.
        /// </summary>
        public static string ConfigSet_ParsePracticeRaceRaceStartResponse {
            get {
                return ResourceManager.GetString("ConfigSet_ParsePracticeRaceRaceStartResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析房间比赛.
        /// </summary>
        public static string ConfigSet_ParseRoomMatchRaceStartResponse {
            get {
                return ResourceManager.GetString("ConfigSet_ParseRoomMatchRaceStartResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析育成事件.
        /// </summary>
        public static string ConfigSet_ParseSingleModeCheckEventResponse {
            get {
                return ResourceManager.GetString("ConfigSet_ParseSingleModeCheckEventResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析竞技场对手属性.
        /// </summary>
        public static string ConfigSet_ParseTeamStadiumOpponentListResponse {
            get {
                return ResourceManager.GetString("ConfigSet_ParseTeamStadiumOpponentListResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析萝卜马胜鞍.
        /// </summary>
        public static string ConfigSet_ParseTrainedCharaLoadResponse {
            get {
                return ResourceManager.GetString("ConfigSet_ParseTrainedCharaLoadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存用于调试的请求通讯包.
        /// </summary>
        public static string ConfigSet_SaveRequestForDebug {
            get {
                return ResourceManager.GetString("ConfigSet_SaveRequestForDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存用于调试的回复通讯包.
        /// </summary>
        public static string ConfigSet_SaveResponseForDebug {
            get {
                return ResourceManager.GetString("ConfigSet_SaveResponseForDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示训练人头信息.
        /// </summary>
        public static string ConfigSet_ShowCommandInfo {
            get {
                return ResourceManager.GetString("ConfigSet_ShowCommandInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回合信息写入文件以方便AI读取.
        /// </summary>
        public static string ConfigSet_WriteAIInfo {
            get {
                return ResourceManager.GetString("ConfigSet_WriteAIInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件信息写入文件以方便AI读取.
        /// </summary>
        public static string ConfigSet_WriteEventInfo {
            get {
                return ResourceManager.GetString("ConfigSet_WriteEventInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动菜单(用↑和↓切换选项,回车确认).
        /// </summary>
        public static string LaunchMenu {
            get {
                return ResourceManager.GetString("LaunchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装游戏加速驱动.
        /// </summary>
        public static string LaunchMenu_InstallNetFilterDriver {
            get {
                return ResourceManager.GetString("LaunchMenu_InstallNetFilterDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动安装ura-core.
        /// </summary>
        public static string LaunchMenu_InstallUraCore {
            get {
                return ResourceManager.GetString("LaunchMenu_InstallUraCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理DMM服务信息.
        /// </summary>
        public static string LaunchMenu_ManageDMMService {
            get {
                return ResourceManager.GetString("LaunchMenu_ManageDMMService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        public static string LaunchMenu_Options {
            get {
                return ResourceManager.GetString("LaunchMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按任意键返回主菜单.
        /// </summary>
        public static string LaunchMenu_Options_BackToMenuInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Options_BackToMenuInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [grey](用[blue]&lt;空格&gt;[/]切换选项,按下[green]&lt;回车&gt;[/]保存并返回,[[X]]为选中状态)[/].
        /// </summary>
        public static string LaunchMenu_Options_Instruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Options_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置本地化文件路径.
        /// </summary>
        public static string LaunchMenu_SetLocalizedDataFilePath {
            get {
                return ResourceManager.GetString("LaunchMenu_SetLocalizedDataFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置加速服务器.
        /// </summary>
        public static string LaunchMenu_SetNetfilterTarget {
            get {
                return ResourceManager.GetString("LaunchMenu_SetNetfilterTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理服务器是否需要认证.
        /// </summary>
        public static string LaunchMenu_SetNetfilterTarget_AskAuth {
            get {
                return ResourceManager.GetString("LaunchMenu_SetNetfilterTarget_AskAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入代理服务器的密码.
        /// </summary>
        public static string LaunchMenu_SetNetfilterTarget_AskAuthPassword {
            get {
                return ResourceManager.GetString("LaunchMenu_SetNetfilterTarget_AskAuthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入代理服务器的用户名.
        /// </summary>
        public static string LaunchMenu_SetNetfilterTarget_AskAuthUsername {
            get {
                return ResourceManager.GetString("LaunchMenu_SetNetfilterTarget_AskAuthUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入代理服务器的地址（默认: 127.0.0.1）.
        /// </summary>
        public static string LaunchMenu_SetNetfilterTarget_AskHost {
            get {
                return ResourceManager.GetString("LaunchMenu_SetNetfilterTarget_AskHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入代理服务器的端口（默认: 1080）.
        /// </summary>
        public static string LaunchMenu_SetNetfilterTarget_AskPort {
            get {
                return ResourceManager.GetString("LaunchMenu_SetNetfilterTarget_AskPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动！.
        /// </summary>
        public static string LaunchMenu_Start {
            get {
                return ResourceManager.GetString("LaunchMenu_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [yellow]正在检测umamusume.exe是否运行[/].
        /// </summary>
        public static string LaunchMenu_Start_Checking {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到umamusume.exe正在运行,直接启动服务器.
        /// </summary>
        public static string LaunchMenu_Start_Checking_AlreadyRunning {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_Checking_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到{0}个正在运行的umamusume.exe.
        /// </summary>
        public static string LaunchMenu_Start_Checking_Found {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_Checking_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [grey]日志: [/] {0}.
        /// </summary>
        public static string LaunchMenu_Start_Checking_Log {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_Checking_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold blue]正在获取DMM Onetime Token[/].
        /// </summary>
        public static string LaunchMenu_Start_GetToken {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在启动umamusume.exe.
        /// </summary>
        public static string LaunchMenu_Start_Launching {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_Launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold green]已启动[/].
        /// </summary>
        public static string LaunchMenu_Start_Started {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取DMM Onetime Token失败.
        /// </summary>
        public static string LaunchMenu_Start_TokenFailed {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_TokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已获取DMM Onetime Token.
        /// </summary>
        public static string LaunchMenu_Start_TokenGot {
            get {
                return ResourceManager.GetString("LaunchMenu_Start_TokenGot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸载游戏加速驱动.
        /// </summary>
        public static string LaunchMenu_UninstallNetFilterDriver {
            get {
                return ResourceManager.GetString("LaunchMenu_UninstallNetFilterDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现新版本程序.
        /// </summary>
        public static string LaunchMenu_Update_AlreadyLatestInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_AlreadyLatestInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敲回车开始更新主程序.
        /// </summary>
        public static string LaunchMenu_Update_BeginUpdateProgramInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_BeginUpdateProgramInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成.
        /// </summary>
        public static string LaunchMenu_Update_DownloadedInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadedInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从GitHub下载最新的events.br.
        /// </summary>
        public static string LaunchMenu_Update_DownloadEventsInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadEventsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从GitHub下载最新的factor_ids.br.
        /// </summary>
        public static string LaunchMenu_Update_DownloadFactorIdsInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadFactorIdsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从GitHub下载最新的names.br.
        /// </summary>
        public static string LaunchMenu_Update_DownloadNamesInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadNamesInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从GitHub下载最新的主程序文件.
        /// </summary>
        public static string LaunchMenu_Update_DownloadProgramInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadProgramInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从GitHub下载最新的skilldata.br.
        /// </summary>
        public static string LaunchMenu_Update_DownloadSkillDataInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadSkillDataInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从GitHub下载最新的successevents.br.
        /// </summary>
        public static string LaunchMenu_Update_DownloadSuccessEventsInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadSuccessEventsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从GitHub下载最新的talentskillsets.br.
        /// </summary>
        public static string LaunchMenu_Update_DownloadTalentSkillInstruction {
            get {
                return ResourceManager.GetString("LaunchMenu_Update_DownloadTalentSkillInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新数据文件.
        /// </summary>
        public static string LaunchMenu_UpdateAssets {
            get {
                return ResourceManager.GetString("LaunchMenu_UpdateAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新程序.
        /// </summary>
        public static string LaunchMenu_UpdateProgram {
            get {
                return ResourceManager.GetString("LaunchMenu_UpdateProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预测总分: {0}(已学习技能) + {1}(即将学习技能) + {2}(属性) = {3}({4}).
        /// </summary>
        public static string MaximiumGradeSkillRecommendation_Caption {
            get {
                return ResourceManager.GetString("MaximiumGradeSkillRecommendation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评价点.
        /// </summary>
        public static string MaximiumGradeSkillRecommendation_Columns_Grade {
            get {
                return ResourceManager.GetString("MaximiumGradeSkillRecommendation_Columns_Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要技能点数.
        /// </summary>
        public static string MaximiumGradeSkillRecommendation_Columns_RequireSP {
            get {
                return ResourceManager.GetString("MaximiumGradeSkillRecommendation_Columns_RequireSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能名.
        /// </summary>
        public static string MaximiumGradeSkillRecommendation_Columns_SkillName {
            get {
                return ResourceManager.GetString("MaximiumGradeSkillRecommendation_Columns_SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总计技能点: {0}, 使用技能点: {1}, 剩余技能点: {2}.
        /// </summary>
        public static string MaximiumGradeSkillRecommendation_Title {
            get {
                return ResourceManager.GetString("MaximiumGradeSkillRecommendation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无选项.
        /// </summary>
        public static string SingleModeCheckEvent_Event_NoOption {
            get {
                return ResourceManager.GetString("SingleModeCheckEvent_Event_NoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知效果.
        /// </summary>
        public static string SingleModeCheckEvent_Event_UnknownEffect {
            get {
                return ResourceManager.GetString("SingleModeCheckEvent_Event_UnknownEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知事件.
        /// </summary>
        public static string SingleModeCheckEvent_Event_UnknownEvent {
            get {
                return ResourceManager.GetString("SingleModeCheckEvent_Event_UnknownEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知选项 @ {0}.
        /// </summary>
        public static string SingleModeCheckEvent_Event_UnknownOption {
            get {
                return ResourceManager.GetString("SingleModeCheckEvent_Event_UnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知来源.
        /// </summary>
        public static string SingleModeCheckEvent_Event_UnknownSource {
            get {
                return ResourceManager.GetString("SingleModeCheckEvent_Event_UnknownSource", resourceCulture);
            }
        }
    }
}
